import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Bot } from "lucide-react";
import BottomBar from "@/components/shared/bottom-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center relative`}>
        {children}
        <BottomBar />
      </body>
    </html>
  );
}
